# Generated by Django 4.0.2 on 2022-02-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='apply',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apply',
            name='grade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apply',
            name='major',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apply',
            name='motive',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='apply',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apply',
            name='passion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='apply',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apply',
            name='positionRe',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='apply',
            name='studentId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apply',
            name='teamwork',
            field=models.TextField(),
        ),
    ]
